### ISSUE TITLE
Moving ulps.exe once it has been installed

### ISSUE THREAD

**Issue by PhilipTsv** [qbsa/ulpc#1]
Hey,

I installed the program to see if it will work, while the files were on my desktop. Then it worked and I moved them, but that stopped the MS Service, since it couldn't find the exe on the desktop any more. Is there a way to change or delete the service? I looked into the registry, but the Enable ULPS Watcher service was not in the Services sub-group of the registry. I also couldn't edit the service itself from the Services window.

Also, is it normal for the process to be taking 5-10% of CPU power on a 8 thread i7 (albeit mobile) chip, just wondering since it seems a lot!

**Comment by qbsa** [comment]
Hi, @PhilipTsv!
Thanks for feedback

> Then it worked and I moved them, but that stopped the MS Service, since it couldn't find the exe on the desktop any more.

This service have installation procedure, which register `ulps.exe` as a service. But it doesn't move executable file to any installation folder like "Program Files", so you shouldn't move service file after running `install.cmd` or `ulps install`. Or uninstall it first with `ulps uninstall` command.

> Is there a way to change or delete the service?

Yes just run the following command: `ulps.exe uninstall`

> Also, is it normal for the process to be taking 5-10% of CPU power on a 8 thread i7 (albeit mobile) chip, just wondering since it seems a lot!

Regarding high CPU usage. This service desined to consume as few resources as possible.
But if you system runs some process which intensively writes to `HKLM\CurrentControlSet\Control\Class` registry branch, it may increase CPU load unfortunately.
